// Generated by MARIGOLD-BATCH-APP (5-field outreach batch).
import type { MarigoldConfig } from "./config";

export const BUSINESS: MarigoldConfig = {
  "businessName": "Cafe Edinburgh",
  "location": "",
  "palette": "marigold-green",
  "fontSet": "fraunces-dmsans",
  "heroImage": "/hero.jpg",
  "aboutQuote": "We opened Cafe Edinburgh to be the kind of place we missed — somewhere warm, where the bread is real, the coffee is strong and nobody is in a rush.",
  "aboutAttribution": "— The owners",
  "phone": "0131 000 0000",
  "email": "info@cafeedinburgh.com",
  "address": [
    "57 High Street",
    "Edinburgh"
  ]
};
